'use client';
import { createContext, useContext, useCallback, useEffect, useId, useReducer, useRef, useState, type ReactNode } from 'react';
import { ArrowDownToLine, Grid2X2, SlidersHorizontal, Undo2, Redo2, RotateCcw, Shuffle, Bookmark, Check, LockKeyhole, LockKeyholeOpen, Monitor, Smartphone, ChevronDown, X, Plus, Trash2, Maximize2, LoaderCircle, Upload, FileDown, RotateCw, Copy, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { original, palettes, preset, applyPreset, parseDesignFile, serializeDesign, presetNames, reducer, randomize, dimensionError, readStorage, writeStorage, type WallpaperRecipe, type Locks, type LockCategory, type SavedDesign } from '@/lib/mat/model';
import { renderMat, exportPng } from '@/lib/mat/render';

const sizes = [{ name: 'Desktop · 4K UHD', width: 3840, height: 2160 }, { name: 'Desktop · Full HD', width: 1920, height: 1080 }, { name: 'Phone · Portrait', width: 1440, height: 3120 }, { name: 'Ultrawide · QHD', width: 3440, height: 1440 }];
const presetRecipes = presetNames.map((_, i) => preset(i));
const EditContext = createContext({ begin: () => {}, commit: () => {} });
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 15000);
}
const format = (value: number) => Number.isInteger(value) ? String(value) : value.toFixed(2).replace(/0$/, '');
function Range({ label, value, min = 0, max = 1, step = .01, unit = '', onChange }: { label: string; value: number; min?: number; max?: number; step?: number; unit?: string; onChange: (n: number) => void }) {
  const id = useId(), edit = useContext(EditContext), scale = unit === '%' ? 100 : 1;
  function accept(input: HTMLInputElement) {
    if (!input.value.trim() || !Number.isFinite(input.valueAsNumber)) { input.value = format(value * scale); return; }
    const next = Math.min(max, Math.max(min, Math.round((input.valueAsNumber / scale - min) / step) * step + min));
    input.value = format(next * scale); onChange(Number(next.toFixed(4)));
  }
  return <div className="range-field"><div className="control-row"><span id={id}>{label}</span><div className="exact-value"><input key={value} type="number" aria-label={`${label} exact value`} min={min * scale} max={max * scale} step={Number((step * scale).toFixed(4))} defaultValue={Number((value * scale).toFixed(4))} onBlur={e => accept(e.currentTarget)} onKeyDown={e => { if (e.key === 'Enter') e.currentTarget.blur(); if (e.key === 'Escape') { e.currentTarget.value = format(value * scale); e.currentTarget.blur(); } }} />{unit && <span>{unit}</span>}</div></div><Slider aria-labelledby={id} value={[value]} min={min} max={max} step={step} onValueChange={v => { edit.begin(); onChange(Array.isArray(v) ? v[0] : v); }} onValueCommitted={() => edit.commit()} onPointerCancel={() => edit.commit()} /></div>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) { const id = useId(); return <div className="toggle-field"><label htmlFor={id}>{label}</label><Switch id={id} checked={value} onCheckedChange={onChange} /></div>; }
function Section({ title, children, extra }: { title: string; children: ReactNode; extra?: ReactNode }) { return <section className="control-section"><div className="section-heading"><h3>{title}</h3>{extra}</div>{children}</section>; }
function MatCanvas({ recipe, small = false, onError }: { recipe: WallpaperRecipe; small?: boolean; onError?: (message: string) => void }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    let frame = 0; const canvas = ref.current; if (!canvas) return;
    const draw = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => {
      const parent = canvas.parentElement; if (!parent) return;
      const ratio = recipe.width / recipe.height, dpr = Math.min(window.devicePixelRatio || 1, 2);
      const availableWidth = small ? parent.clientWidth : Math.max(40, parent.clientWidth - (window.innerWidth < 760 ? 32 : 68));
      const availableHeight = small ? parent.clientHeight : Math.max(40, parent.clientHeight - (window.innerWidth < 760 ? 32 : 68));
      const displayWidth = Math.min(availableWidth, availableHeight * ratio);
      canvas.style.width = `${displayWidth}px`; canvas.style.height = `${displayWidth / ratio}px`;
      const width = Math.max(1, Math.round(displayWidth * dpr));
      try { renderMat(canvas, recipe, width, Math.max(1, Math.round(width / ratio))); } catch (error) { onError?.(error instanceof Error ? error.message : 'Preview could not be drawn.'); }
    }); };
    const observer = new ResizeObserver(draw); if (canvas.parentElement) observer.observe(canvas.parentElement); draw();
    return () => { observer.disconnect(); cancelAnimationFrame(frame); };
  }, [recipe, small, onError]);
  // Canvas is the actual image surface; an img element cannot host the live drawing.
  // oxlint-disable-next-line jsx-a11y/prefer-tag-over-role
  return <canvas ref={ref} role="img" aria-label={`${recipe.name}, ${recipe.palette.name} cutting-mat wallpaper${small ? '' : ' live preview'}`} />;
}
export default function Home() {
  const [history, dispatch] = useReducer(reducer, { past: [], present: original, future: [] }); const r = history.present;
  const [tab, setTab] = useState('Grid'); const [ready, setReady] = useState(false); const [saved, setSaved] = useState<SavedDesign[]>([]);
  const importInput = useRef<HTMLInputElement>(null);
  const [keepCanvas, setKeepCanvas] = useState(true);
  const [activeSavedId, setActiveSavedId] = useState<string | null>(null);
  const [deletedDesign, setDeletedDesign] = useState<SavedDesign | null>(null);
  const [savedOpen, setSavedOpen] = useState(false); const [saveName, setSaveName] = useState('My cutting mat');
  const [message, setMessage] = useState(''); const [storageError, setStorageError] = useState(false); const [exporting, setExporting] = useState(false);
  const [custom, setCustom] = useState(false); const [draftSize, setDraftSize] = useState({ width: String(original.width), height: String(original.height) });
  const [locks, setLocks] = useState<Locks>({ palette: false, grid: false, guides: false, material: false }); const [expanded, setExpanded] = useState(false);
  const errorHandler = useCallback((text: string) => setMessage(text), []);
  const set = (recipe: WallpaperRecipe) => dispatch({ type: 'set', recipe });
  function update<K extends 'grid' | 'guides' | 'palette' | 'typography' | 'material' | 'quiet'>(section: K, patch: Partial<WallpaperRecipe[K]>) { set({ ...r, name: 'Custom', [section]: { ...r[section], ...patch } }); }
  // Read browser-only persistence after hydration.
  // oxlint-disable-next-line react/react-compiler
  useEffect(() => { try { const loaded = readStorage(localStorage); if (loaded.recipe) dispatch({ type: 'restore', recipe: loaded.recipe }); setSaved(loaded.saved); setStorageError(loaded.error); } catch { setStorageError(true); } setReady(true); }, []);
  useEffect(() => { if (!ready) return; const persist = () => { try { if (!writeStorage(localStorage, 'cutting-mat:latest', r)) setStorageError(true); } catch { setStorageError(true); } }; const timer = setTimeout(persist, 300); window.addEventListener('pagehide', persist); return () => { clearTimeout(timer); window.removeEventListener('pagehide', persist); }; }, [r, ready]);
  // Synchronize the editable dimension draft after preset changes and undo/redo.
  // oxlint-disable-next-line react/react-compiler
  useEffect(() => { setDraftSize({ width: String(r.width), height: String(r.height) }); setCustom(!sizes.some(s => s.width === r.width && s.height === r.height)); }, [r.width, r.height]);
  useEffect(() => { if (!message) return; const timer = setTimeout(() => setMessage(''), 6500); return () => clearTimeout(timer); }, [message]);
  useEffect(() => { const listener = (event: KeyboardEvent) => {
    if (event.key === 'Escape') { setExpanded(false); setSavedOpen(false); }
    if ((event.target as HTMLElement)?.closest('input, textarea, [contenteditable="true"], [role="slider"]')) return;
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); dispatch({ type: event.shiftKey ? 'redo' : 'undo' }); }
  }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, []);
  useEffect(() => { if (savedOpen) { const frame = requestAnimationFrame(() => document.getElementById('saved-designs')?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })); return () => cancelAnimationFrame(frame); } }, [savedOpen]);
  const sizeError = custom ? dimensionError(Number(draftSize.width), Number(draftSize.height)) : null;
  const sizePending = custom && (Number(draftSize.width) !== r.width || Number(draftSize.height) !== r.height);
  function commitSize() { const width = Number(draftSize.width), height = Number(draftSize.height); const error = dimensionError(width, height); if (error) { setMessage(error); return; } set({ ...r, width, height }); }
  function saveDesign(replace = false) {
    const name = saveName.trim(); if (!name) { setMessage('Give your design a name first.'); return; }
    if (!replace && saved.length >= 30) { setMessage('You have 30 saved designs. Remove one to make room.'); return; }
    const id = replace && activeSavedId ? activeSavedId : crypto.randomUUID();
    const entry = { id, name, recipe: r };
    const next = replace && activeSavedId ? saved.map(row => row.id === id ? entry : row) : [entry, ...saved];
    try { if (!writeStorage(localStorage, 'cutting-mat:saved', next)) throw Error(); setSaved(next); setActiveSavedId(id); setMessage(replace ? 'Saved design updated.' : 'Design saved on this device.'); } catch { setStorageError(true); setMessage('This browser could not save the design. You can still export your wallpaper.'); }
  }
  function deleteDesign(id: string) { const next = saved.filter(s => s.id !== id); try { if (!writeStorage(localStorage, 'cutting-mat:saved', next)) throw Error(); setDeletedDesign(saved.find(s => s.id === id) ?? null); setSaved(next); if (activeSavedId === id) setActiveSavedId(null); } catch { setMessage('Could not update device storage.'); } }
  function restoreDeleted() {
    if (!deletedDesign || saved.length >= 30) return;
    const next = [deletedDesign, ...saved];
    try { if (!writeStorage(localStorage, 'cutting-mat:saved', next)) throw Error(); setSaved(next); setDeletedDesign(null); } catch { setMessage('Could not restore the saved design.'); }
  }
  async function importDesign(file?: File) {
    if (!file) return;
    try { if (file.size > 65536) throw new Error('Choose a Cutting Mat design file smaller than 64 KB.'); const recipe = parseDesignFile(await file.text()); set(recipe); setActiveSavedId(null); setSaveName(recipe.name === 'Custom' ? 'Imported mat' : recipe.name); setMessage('Design imported. All settings are editable; undo returns to your previous mat.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'This design could not be imported.'); }
  }
  function exportDesign() { downloadBlob(new Blob([serializeDesign(r)], { type: 'application/json' }), 'cutting-mat.design.json'); setMessage('Editable design downloaded. Import it on another device to keep working.'); }
  function matchScreen() {
    const width = Math.round(window.screen.width * window.devicePixelRatio), height = Math.round(window.screen.height * window.devicePixelRatio);
    const error = dimensionError(width, height); if (error) { setMessage(error); return; } set({ ...r, width, height }); setMessage(`Canvas matched to ${width} × ${height}. Browser zoom can affect this estimate.`);
  }
  async function download() {
    if (exporting || sizeError || sizePending) return;
    const recipe = r;
    setExporting(true); setMessage('');
    try {
      await new Promise(resolve => setTimeout(resolve, 60)); const blob = await exportPng(recipe);
      downloadBlob(blob, `cutting-mat-${recipe.palette.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${recipe.width}x${recipe.height}.png`); setMessage('Wallpaper ready. Your PNG download has started.');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Export failed. Try a smaller canvas.'); } finally { setExporting(false); }
  }
  function lockButton(category: LockCategory) { const locked = locks[category]; return <Button variant="ghost" size="icon-xs" aria-label={`${locked ? 'Unlock' : 'Lock'} ${category} during randomization`} aria-pressed={locked} title={`${locked ? 'Unlock' : 'Lock'} for shuffle`} onClick={() => setLocks({ ...locks, [category]: !locked })}>{locked ? <LockKeyhole className="locked" /> : <LockKeyholeOpen />}</Button>; }
  return <EditContext.Provider value={{ begin: () => dispatch({ type: 'begin' }), commit: () => dispatch({ type: 'commit' }) }}><main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-icon"><Grid2X2 size={22} strokeWidth={1.2} /></div><div><h1>Cutting Mat<span className="edition">STUDIO</span></h1><p>A little structure for your screen.</p></div></div><div className="header-actions"><Button variant="ghost" className="saved-trigger" aria-expanded={savedOpen} onClick={() => setSavedOpen(!savedOpen)}><Bookmark size={15} /><span>Saved designs</span>{saved.length > 0 && <span className="count">{saved.length}</span>}</Button><Button className="export-button" onClick={download} disabled={exporting || !!sizeError || sizePending}>{exporting ? <LoaderCircle className="spin" /> : <ArrowDownToLine />}<span>{exporting ? 'Preparing PNG…' : 'Export wallpaper'}</span></Button></div></header>
    <div className="workspace"><section className="main-column">
      <div className="workspace-heading"><div><span className="eyebrow">YOUR WORK SURFACE</span><h2>Room for precision.</h2></div><div className="preview-actions"><span className="live-badge"><i /> LIVE PREVIEW</span><div className="history-actions"><Button variant="ghost" size="icon" aria-label="Undo" title="Undo (⌘/Ctrl Z)" disabled={!history.past.length} onClick={() => dispatch({ type: 'undo' })}><Undo2 /></Button><Button variant="ghost" size="icon" aria-label="Redo" title="Redo (⌘/Ctrl Shift Z)" disabled={!history.future.length} onClick={() => dispatch({ type: 'redo' })}><Redo2 /></Button></div></div></div>
      <div className={`preview-wrap ${expanded ? 'expanded-preview' : ''}`}><div className="preview-stage"><MatCanvas recipe={r} onError={errorHandler} /><Button variant="ghost" size="icon" className="expand-button" aria-label={expanded ? 'Close expanded preview' : 'Expand preview'} aria-pressed={expanded} onClick={() => setExpanded(!expanded)}>{expanded ? <X /> : <Maximize2 />}</Button></div></div>
      <div className="preview-caption"><span>{r.name.toUpperCase()} <b>/</b> {r.palette.name.toUpperCase()}</span><span>{r.width} × {r.height} PX <b>·</b> PNG</span></div>
      <div className="presets-heading"><h3>A starting point.</h3><p>Make it yours from here.</p><label className="keep-canvas" htmlFor="keep-canvas"><Switch id="keep-canvas" size="sm" checked={keepCanvas} onCheckedChange={setKeepCanvas} aria-label="Keep canvas size when applying presets" />Keep canvas size</label></div><div className="preset-grid">{presetRecipes.map((p, i) => <button className={`preset-card ${r.name === p.name ? 'selected' : ''}`} key={p.name} onClick={() => set(applyPreset(i, r, keepCanvas))} aria-pressed={r.name === p.name}><div className="preset-image" style={{ background: p.palette.background }}><MatCanvas recipe={p} small />{r.name === p.name && <span className="preset-check"><Check size={10} /></span>}</div><span className="preset-label">{p.name}<small>{String(i + 1).padStart(2, '0')}</small></span></button>)}</div>
      <div className="studio-note"><span className="small-cross">+</span><p>Drawn with math. Made for your screen.</p><span>NO AI. JUST GOOD GEOMETRY.</span></div>
      {savedOpen && <section id="saved-designs" className="saved-panel" aria-label="Saved designs"><div className="saved-heading"><div><h3>Your collection</h3><p>Saved in this browser, on this device.</p></div><Button variant="ghost" size="icon" aria-label="Close saved designs" onClick={() => setSavedOpen(false)}><X /></Button></div><div className="design-file-actions"><Button variant="outline" onClick={() => importInput.current?.click()}><Upload />Import design</Button><Button variant="outline" onClick={exportDesign}><FileDown />Download design</Button><input ref={importInput} className="sr-only" type="file" accept=".json,application/json" aria-label="Import Cutting Mat design file" onChange={e => { void importDesign(e.target.files?.[0]); e.target.value = ''; }} /></div><p className="portable-note">Design files keep every setting editable, including your texture pattern.</p><div className="save-form"><Input aria-label="Design name" maxLength={100} value={saveName} onChange={e => setSaveName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') saveDesign(); }} /><Button onClick={() => saveDesign()}><Plus /> Save new</Button>{activeSavedId && <Button variant="secondary" aria-label="Update loaded saved design" onClick={() => saveDesign(true)}><Save />Update</Button>}</div>{saved.length ? <div className="saved-list">{saved.map(s => <div className="saved-item" key={s.id}><button onClick={() => { set(s.recipe); setActiveSavedId(s.id); setSaveName(s.name); setMessage(`Loaded “${s.name}”.`); }}><span className="saved-thumbnail"><MatCanvas recipe={s.recipe} small /></span><span>{s.name}<small>{s.recipe.width} × {s.recipe.height}</small></span></button><Button variant="ghost" size="icon" aria-label={`Duplicate ${s.name}`} onClick={() => { if (saved.length >= 30) { setMessage('Remove a saved design to make room.'); return; } const next = [{ ...s, id: crypto.randomUUID(), name: `${s.name.slice(0, 94)} copy` }, ...saved]; try { if (!writeStorage(localStorage, 'cutting-mat:saved', next)) throw Error(); setSaved(next); } catch { setMessage('Could not duplicate this design.'); } }}><Copy /></Button><Button variant="ghost" size="icon" aria-label={`Delete ${s.name}`} onClick={() => deleteDesign(s.id)}><Trash2 /></Button></div>)}</div> : <p className="empty-note">Your next favorite starts here. Save this mat to keep it.</p>}{deletedDesign && <div className="deleted-notice"><span>“{deletedDesign.name}” removed.</span><Button variant="ghost" disabled={saved.length >= 30} onClick={restoreDeleted}>Undo delete</Button></div>}</section>}
    </section>
    <aside className="settings" aria-label="Wallpaper settings"><div className="settings-title"><SlidersHorizontal size={16} /><h2>Make it yours</h2><Button variant="ghost" size="icon-xs" title="Reset to Original (can be undone)" aria-label="Reset to original" onClick={() => { set(preset(0)); setMessage('Reset to Original. Undo is available.'); }}><RotateCcw /></Button></div>
      <Section title="Canvas"><div className="select-wrap">{r.height > r.width ? <Smartphone size={15} /> : <Monitor size={15} />}<select aria-label="Canvas size" value={custom ? 'custom' : `${r.width}x${r.height}`} onChange={e => { if (e.target.value === 'custom') { setCustom(true); return; } const [width, height] = e.target.value.split('x').map(Number); setCustom(false); set({ ...r, width, height }); }}>{sizes.map(s => <option value={`${s.width}x${s.height}`} key={s.name}>{s.name}</option>)}<option value="custom">Custom dimensions</option></select><ChevronDown size={13} /></div>{custom ? <><div className="dimension-inputs"><label htmlFor="canvas-width">Width<Input id="canvas-width" type="number" min={64} max={8192} value={draftSize.width} onChange={e => setDraftSize({ ...draftSize, width: e.target.value })} aria-invalid={!!sizeError} /></label><span>×</span><label htmlFor="canvas-height">Height<Input id="canvas-height" type="number" min={64} max={8192} value={draftSize.height} onChange={e => setDraftSize({ ...draftSize, height: e.target.value })} aria-invalid={!!sizeError} /></label></div>{sizeError && <p className="field-error">{sizeError}</p>}<Button variant="secondary" className="full-button" disabled={!!sizeError} onClick={commitSize}>Apply dimensions</Button></> : <p className="field-hint">{r.width} × {r.height} pixels <span>{(r.width / r.height).toFixed(2)}:1</span></p>}<div className="canvas-tools"><Button variant="outline" onClick={matchScreen}><Monitor />My screen</Button><Button variant="outline" onClick={() => set({ ...r, width: r.height, height: r.width })}><RotateCw />Rotate</Button></div>{sizePending && !sizeError && <p className="field-hint">Apply dimensions above to update the preview and enable export.</p>}</Section>
      <Section title="Color palette" extra={lockButton('palette')}><div className="palette-grid">{palettes.map(p => <button key={p.name} className={`swatch ${r.palette.name === p.name ? 'active' : ''}`} style={{ background: p.background }} title={p.name} aria-label={`${p.name} palette`} aria-pressed={r.palette.name === p.name} onClick={() => update('palette', p)}>{r.palette.name === p.name && <Check size={12} style={{ color: p.label }} />}</button>)}</div><div className="palette-name"><span>{r.palette.name}</span><span>{r.palette.background.toUpperCase()}</span></div><details className="fine-details"><summary>Fine-tune colors<Plus size={11} /></summary><div className="color-fields">{(['background', 'grid', 'label', 'accent'] as const).map(key => <label key={key}><input type="color" value={r.palette[key]} aria-label={`${key} color`} onChange={e => update('palette', { [key]: e.target.value, name: 'Custom palette' })} /><span>{key === 'label' ? 'Labels' : key}</span><code>{r.palette[key]}</code></label>)}</div></details></Section>
      <div className="control-tabs" role="tablist" aria-label="Setting categories">{['Grid', 'Guides', 'Finish'].map(t => <button key={t} id={`tab-${t}`} role="tab" aria-selected={tab === t} aria-controls={`panel-${t}`} tabIndex={tab === t ? 0 : -1} onClick={() => setTab(t)} onKeyDown={e => { const tabs = ['Grid', 'Guides', 'Finish']; const current = tabs.indexOf(tab); const next = e.key === 'ArrowRight' ? (current + 1) % 3 : e.key === 'ArrowLeft' ? (current + 2) % 3 : -1; if (next >= 0) { e.preventDefault(); setTab(tabs[next]); document.getElementById(`tab-${tabs[next]}`)?.focus(); } }}>{t}</button>)}</div>
      <div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
      {tab === 'Grid' && <Section title="Grid system" extra={lockButton('grid')}><Range label="Spacing" value={r.grid.spacing} min={12} max={80} step={1} onChange={v => update('grid', { spacing: v })} /><Range label="Major line every" value={r.grid.majorEvery} min={2} max={10} step={1} unit=" cells" onChange={v => update('grid', { majorEvery: v })} /><div className="segmented" aria-label="Grid line style"><Button variant="ghost" aria-pressed={!r.grid.dotted} onClick={() => update('grid', { dotted: false })}><span className="solid-line" />Solid</Button><Button variant="ghost" aria-pressed={r.grid.dotted} onClick={() => update('grid', { dotted: true })}><span className="dotted-line" />Dotted</Button></div><details className="fine-details" open><summary>Line appearance<ChevronDown size={12} /></summary><Range label="Minor opacity" value={r.grid.minorOpacity} unit="%" onChange={v => update('grid', { minorOpacity: v })} /><Range label="Major opacity" value={r.grid.majorOpacity} unit="%" onChange={v => update('grid', { majorOpacity: v })} /><Range label="Minor weight" value={r.grid.minorWidth} min={.2} max={2} step={.05} onChange={v => update('grid', { minorWidth: v })} /><Range label="Major weight" value={r.grid.majorWidth} min={.3} max={3} step={.1} onChange={v => update('grid', { majorWidth: v })} /></details><details className="fine-details"><summary>Grid origin<Plus size={11} /></summary><Range label="Horizontal offset" value={r.grid.offsetX} min={0} max={100} step={1} onChange={v => update('grid', { offsetX: v })} /><Range label="Vertical offset" value={r.grid.offsetY} min={0} max={100} step={1} onChange={v => update('grid', { offsetY: v })} /><p className="field-hint">Offset as a percentage of one grid cell.</p></details></Section>}
      {tab === 'Guides' && <Section title="Precision markings" extra={lockButton('guides')}><div className="sub-label">EDGE RULERS</div>{(['top', 'left', 'right', 'bottom'] as const).map(key => <Toggle key={key} label={`${key[0].toUpperCase()}${key.slice(1)} ruler`} value={r.guides[key]} onChange={v => update('guides', { [key]: v })} />)}<div className="sub-label spaced">ANGLE GUIDES</div>{([30, 45, 60] as const).map(angle => <Toggle key={angle} label={`${angle}° diagonal`} value={r.guides[`angle${angle}`]} onChange={v => update('guides', { [`angle${angle}`]: v })} />)}<div className="sub-label spaced">TEMPLATES</div><Toggle label="Circle templates" value={r.guides.circles} onChange={v => update('guides', { circles: v })} /><Toggle label="Inset border" value={r.guides.border} onChange={v => update('guides', { border: v })} /><p className="field-hint ruler-note">Ruler markings are decorative, not calibrated physical measurements.</p></Section>}
      {tab === 'Finish' && <><Section title="Surface material" extra={lockButton('material')}><Range label="Surface grain" value={r.material.grain} unit="%" onChange={v => update('material', { grain: v })} /><Range label="Wear & blade marks" value={r.material.wear} unit="%" onChange={v => update('material', { wear: v })} /><div className="range-endpoints"><span>PRISTINE</span><span>WELL USED</span></div><Button variant="outline" className="full-button" onClick={() => update('material', { seed: Math.floor(Math.random() * 2147483647) })}><Shuffle />New wear pattern</Button><p className="field-hint">Pattern {r.material.seed} · stays fixed while editing</p></Section><Section title="Corner legend"><label className="text-field" htmlFor="legend-title">Title<Input id="legend-title" value={r.typography.title} maxLength={80} onChange={e => update('typography', { title: e.target.value })} /></label><label className="text-field" htmlFor="legend-subtitle">Subtitle<Input id="legend-subtitle" value={r.typography.subtitle} maxLength={120} onChange={e => update('typography', { subtitle: e.target.value })} /></label><Range label="Type size" value={r.typography.size} min={8} max={30} step={1} onChange={v => update('typography', { size: v })} /><Range label="Legend opacity" value={r.typography.opacity} unit="%" onChange={v => update('typography', { opacity: v })} /></Section></>}
      </div>
      <Section title="A little breathing room"><Toggle label="Quiet zone" value={r.quiet.enabled} onChange={v => update('quiet', { enabled: v })} /><p className="field-hint">Soften the grid behind your clock or icons.</p>{r.quiet.enabled && <div className="quiet-controls"><Range label="Horizontal position" value={r.quiet.x} min={0} max={100} step={1} onChange={v => update('quiet', { x: v })} /><Range label="Vertical position" value={r.quiet.y} min={0} max={100} step={1} onChange={v => update('quiet', { y: v })} /><Range label="Zone width" value={r.quiet.width} min={5} max={100} step={1} onChange={v => update('quiet', { width: v })} /><Range label="Zone height" value={r.quiet.height} min={5} max={100} step={1} onChange={v => update('quiet', { height: v })} /><Range label="Fade strength" value={r.quiet.strength} unit="%" onChange={v => update('quiet', { strength: v })} /></div>}</Section>
      <div className="shuffle-section"><Button variant="outline" className="shuffle-button" onClick={() => { set(randomize(r, locks, Math.floor(Math.random() * 2147483647))); setMessage('A fresh combination. Locked settings kept.'); }} disabled={Object.values(locks).every(Boolean)}><Shuffle size={14} /> Surprise me <span>↗</span></Button><p>Lock what you love. Shuffle the rest.</p><div className="lock-chips">{(['palette', 'grid', 'guides', 'material'] as const).map(key => <button key={key} aria-label={`${locks[key] ? 'Unlock' : 'Lock'} ${key}`} aria-pressed={locks[key]} onClick={() => setLocks({ ...locks, [key]: !locks[key] })}>{locks[key] ? <LockKeyhole size={10} /> : <LockKeyholeOpen size={10} />}{key}</button>)}</div></div>
    </aside></div>
    <footer className="footer"><span><Grid2X2 size={11} /> CUTTING MAT STUDIO <b> / </b> V.02</span><span>{storageError ? 'Device storage unavailable · PNG export still works' : 'Made locally. Saved on this device.'}</span></footer>
    <output className={`toast ${message ? 'visible' : ''}`} aria-live="polite">{message}<button aria-label="Dismiss notification" tabIndex={message ? 0 : -1} onClick={() => setMessage('')}><X size={14} /></button></output>
  </main></EditContext.Provider>;
}
